### ISSUE TITLE
grid_lvis_l2.py crashing when attempting to follow example

### ISSUE THREAD

**Issue by serbinsh** [zhanlilz/grid-nasa-lvis-l2#1]
I am attempting to test run this code to allow me to rasterize LVIS data from the 2019 ABoVE flights. However I am as of yet unable to get this to run all the way through, even with the example provided

```
(/data2/sserbin/conda_envs/geospatial) [sserbin@modex LVIS]$ python grid-nasa-lvis-l2/grid_lvis_l2.py -r 20 --out_srs EPSG:3156 --column_type lvis_l2_column_types.csvt \
> --column2grid rh10 -- LVIS2_ABoVE2017_0630_R1803_069010.TXT LVIS2_ABoVE2017_0630_R1803_069010_grid_points.sqlite

bash grid-nasa-lvis-l2/vectorize_lvis_l2.sh LVIS2_ABoVE2017_0630_R1803_069010.TXT LVIS2_ABoVE2017_0630_R1803_069010_points.shp lvis_l2_column_types.csvt

LVIS2_ABoVE2017_0630_R1803_069010_points.shp <- LVIS2_ABoVE2017_0630_R1803_069010.TXT
ogr2ogr -overwrite -f ESRI Shapefile -oo X_POSSIBLE_NAMES=GLON -oo Y_POSSIBLE_NAMES=GLAT -a_srs GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.01745329251994328,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4326"]] LVIS2_ABoVE2017_0630_R1803_069010_points.shp ./tmp.AqUwiU4fIu.csv
Warning 6: Normalized/laundered field name: 'INCIDENTANGLE' to 'INCIDENTAN'

ogr2ogr -overwrite -f ESRI Shapefile -dialect SQLite -sql SELECT *, ST_X(geometry) as geasting, ST_Y(geometry) as gnorthing FROM tmp LVIS2_ABoVE2017_0630_R1803_069010_points_proj.shp tmp9q10iom2/tmp.shp

	- 'VirtualXPath'	[XML Path Language - XPath]
	- 'VirtualXPath'	[XML Path Language - XPath]

ogr2ogr -overwrite -sql SELECT ST_Buffer(geometry, 10.000000), * FROM LVIS2_ABoVE2017_0630_R1803_069010_points_proj -dialect SQLITE LVIS2_ABoVE2017_0630_R1803_069010_shot_circles.shp LVIS2_ABoVE2017_0630_R1803_069010_points_proj.shp

	- 'VirtualXPath'	[XML Path Language - XPath]
	- 'VirtualXPath'	[XML Path Language - XPath]

python grid-nasa-lvis-l2/rasterize_vector.py --at --burn 1 -l LVIS2_ABoVE2017_0630_R1803_069010_shot_circles -f GTiff --ot Byte --init 0 --nodata 0 -r 20.0 LVIS2_ABoVE2017_0630_R1803_069010_shot_circles.shp LVIS2_ABoVE2017_0630_R1803_069010_shot_cover.tif

gdal_rasterize -l LVIS2_ABoVE2017_0630_R1803_069010_shot_circles -a_nodata 0.0 -init 0.0 -ot Byte -burn 1.0 -at -tr 20.0 20.0 LVIS2_ABoVE2017_0630_R1803_069010_shot_circles.shp LVIS2_ABoVE2017_0630_R1803_069010_shot_cover.tif
0...10...20...30...40...50...60...70...80...90...100 - done.

bash grid-nasa-lvis-l2/raster_to_polygon_grids.sh LVIS2_ABoVE2017_0630_R1803_069010_shot_cover.tif LVIS2_ABoVE2017_0630_R1803_069010_shot_cover.shp

Input file size is 437, 380
0...10...20...30...40...50...60...70...80...90...100 - done.
ERROR 1: Translating source or target SRS failed:

BOUNDCRS[
    SOURCECRS[
        PROJCRS["unknown",
            BASEGEOGCRS["unknown",
                DATUM["Unknown based on GRS80 ellipsoid",
                    ELLIPSOID["GRS 1980",6378137,298.257222101,
                        LENGTHUNIT["metre",1],
                        ID["EPSG",7019]]],
                PRIMEM["Greenwich",0,
                    ANGLEUNIT["degree",0.0174532925199433],
                    ID["EPSG",8901]]],
            CONVERSION["UTM zone 9N",
                METHOD["Transverse Mercator",
                    ID["EPSG",9807]],
                PARAMETER["Latitude of natural origin",0,
                    ANGLEUNIT["degree",0.0174532925199433],
                    ID["EPSG",8801]],
                PARAMETER["Longitude of natural origin",-129,
                    ANGLEUNIT["degree",0.0174532925199433],
                    ID["EPSG",8802]],
                PARAMETER["Scale factor at natural origin",0.9996,
                    SCALEUNIT["unity",1],
                    ID["EPSG",8805]],
                PARAMETER["False easting",500000,
                    LENGTHUNIT["metre",1],
                    ID["EPSG",8806]],
                PARAMETER["False northing",0,
                    LENGTHUNIT["metre",1],
                    ID["EPSG",8807]],
                ID["EPSG",16009]],
            CS[Cartesian,2],
                AXIS["(E)",east,
                    ORDER[1],
                    LENGTHUNIT["metre",1,
                        ID["EPSG",9001]]],
                AXIS["(N)",north,
                    ORDER[2],
                    LENGTHUNIT["metre",1,
                        ID["EPSG",9001]]]]],
    TARGETCRS[
        GEOGCRS["WGS 84",
            DATUM["World Geodetic System 1984",
                ELLIPSOID["WGS 84",6378137,298.257223563,
                    LENGTHUNIT["metre",1]]],
            PRIMEM["Greenwich",0,
                ANGLEUNIT["degree",0.0174532925199433]],
            CS[ellipsoidal,2],
                AXIS["latitude",north,
                    ORDER[1],
                    ANGLEUNIT["degree",0.0174532925199433]],
                AXIS["longitude",east,
                    ORDER[2],
                    ANGLEUNIT["degree",0.0174532925199433]],
            ID["EPSG",4326]]],
    ABRIDGEDTRANSFORMATION["Transformation from unknown to WGS84",
        METHOD["Position Vector transformation (geog2D domain)",
            ID["EPSG",9606]],
        PARAMETER["X-axis translation",0,
            ID["EPSG",8605]],
        PARAMETER["Y-axis translation",0,
            ID["EPSG",8606]],
        PARAMETER["Z-axis translation",0,
            ID["EPSG",8607]],
        PARAMETER["X-axis rotation",0,
            ID["EPSG",8608]],
        PARAMETER["Y-axis rotation",0,
            ID["EPSG",8609]],
        PARAMETER["Z-axis rotation",0,
            ID["EPSG",8610]],
        PARAMETER["Scale difference",1,
            ID["EPSG",8611]]]]
ERROR 1: Failed to process SRS definition:
BOUNDCRS[
    SOURCECRS[
        PROJCRS["unknown",
            BASEGEOGCRS["unknown",
                DATUM["Unknown based on GRS80 ellipsoid",
                    ELLIPSOID["GRS 1980",6378137,298.257222101,
                        LENGTHUNIT["metre",1],
                        ID["EPSG",7019]]],
                PRIMEM["Greenwich",0,
                    ANGLEUNIT["degree",0.0174532925199433],
                    ID["EPSG",8901]]],
            CONVERSION["UTM zone 9N",
                METHOD["Transverse Mercator",
                    ID["EPSG",9807]],
                PARAMETER["Latitude of natural origin",0,
                    ANGLEUNIT["degree",0.0174532925199433],
                    ID["EPSG",8801]],
                PARAMETER["Longitude of natural origin",-129,
                    ANGLEUNIT["degree",0.0174532925199433],
                    ID["EPSG",8802]],
                PARAMETER["Scale factor at natural origin",0.9996,
                    SCALEUNIT["unity",1],
                    ID["EPSG",8805]],
                PARAMETER["False easting",500000,
                    LENGTHUNIT["metre",1],
                    ID["EPSG",8806]],
                PARAMETER["False northing",0,
                    LENGTHUNIT["metre",1],
                    ID["EPSG",8807]],
                ID["EPSG",16009]],
            CS[Cartesian,2],
                AXIS["(E)",east,
                    ORDER[1],
                    LENGTHUNIT["metre",1,
                        ID["EPSG",9001]]],
                AXIS["(N)",north,
                    ORDER[2],
                    LENGTHUNIT["metre",1,
                        ID["EPSG",9001]]]]],
    TARGETCRS[
        GEOGCRS["WGS 84",
            DATUM["World Geodetic System 1984",
                ELLIPSOID["WGS 84",6378137,298.257223563,
                    LENGTHUNIT["metre",1]]],
            PRIMEM["Greenwich",0,
                ANGLEUNIT["degree",0.0174532925199433]],
            CS[ellipsoidal,2],
                AXIS["latitude",north,
                    ORDER[1],
                    ANGLEUNIT["degree",0.0174532925199433]],
                AXIS["longitude",east,
                    ORDER[2],
                    ANGLEUNIT["degree",0.0174532925199433]],
            ID["EPSG",4326]]],
    ABRIDGEDTRANSFORMATION["Transformation from unknown to WGS84",
        METHOD["Position Vector transformation (geog2D domain)",
            ID["EPSG",9606]],
        PARAMETER["X-axis translation",0,
            ID["EPSG",8605]],
        PARAMETER["Y-axis translation",0,
            ID["EPSG",8606]],
        PARAMETER["Z-axis translation",0,
            ID["EPSG",8607]],
        PARAMETER["X-axis rotation",0,
            ID["EPSG",8608]],
        PARAMETER["Y-axis rotation",0,
            ID["EPSG",8609]],
        PARAMETER["Z-axis rotation",0,
            ID["EPSG",8610]],
        PARAMETER["Scale difference",1,
            ID["EPSG",8611]]]]

bash grid-nasa-lvis-l2/grids_cut_shots.sh LVIS2_ABoVE2017_0630_R1803_069010_shot_cover.shp LVIS2_ABoVE2017_0630_R1803_069010_shot_circles.shp LVIS2_ABoVE2017_0630_R1803_069010_shot_segments.sqlite

ogrmerge.py -f SQLite -overwrite_ds -o ./tmp.LZvUxfcFi4/tmp.nLAY5d1bsA.sqlite LVIS2_ABoVE2017_0630_R1803_069010_shot_circles.shp LVIS2_ABoVE2017_0630_R1803_069010_shot_cover.shp -nln {LAYER_NAME} -dsco SPATIALITE=YES -lco SPATIAL_INDEX=YES
	- 'VirtualXPath'	[XML Path Language - XPath]
ERROR: Cannot open LVIS2_ABoVE2017_0630_R1803_069010_shot_cover.shp
grid-nasa-lvis-l2/grids_cut_shots.sh: line 50: fio: command not found
grid-nasa-lvis-l2/grids_cut_shots.sh: line 50: jq: command not found
grid-nasa-lvis-l2/grids_cut_shots.sh: line 51: fio: command not found
grid-nasa-lvis-l2/grids_cut_shots.sh: line 51: jq: command not found
ogr2ogr -gt 1000000 -f SQLite -overwrite -sql SELECT
ST_Intersection(grd.geometry, buf.geometry) AS geometry, ,
FROM LVIS2_ABoVE2017_0630_R1803_069010_shot_cover AS grd, LVIS2_ABoVE2017_0630_R1803_069010_shot_circles AS buf
WHERE buf.ROWID IN (
SELECT ROWID
FROM SpatialIndex
WHERE f_table_name = 'LVIS2_ABoVE2017_0630_R1803_069010_shot_circles' AND search_frame = grd.geometry
) AND ST_Intersects(grd.geometry, buf.geometry) = 1 -dialect SQLITE ./tmp.LZvUxfcFi4/tmp.7smTlSCJXd.sqlite ./tmp.LZvUxfcFi4/tmp.nLAY5d1bsA.sqlite -dsco SPATIALITE=YES -lco SPATIAL_INDEX=YES -nln LVIS2_ABoVE2017_0630_R1803_069010_shot_segments -nlt POLYGON
	- 'VirtualXPath'	[XML Path Language - XPath]
	- 'VirtualXPath'	[XML Path Language - XPath]
ERROR 1: In ExecuteSQL(): sqlite3_prepare_v2(SELECT
ST_Intersection(grd.geometry, buf.geometry) AS geometry, ,
FROM LVIS2_ABoVE2017_0630_R1803_069010_shot_cover AS grd, LVIS2_ABoVE2017_0630_R1803_069010_shot_circles AS buf
WHERE buf.ROWID IN (
SELECT ROWID
FROM SpatialIndex
WHERE f_table_name = 'LVIS2_ABoVE2017_0630_R1803_069010_shot_circles' AND search_frame = grd.geometry
) AND ST_Intersects(grd.geometry, buf.geometry) = 1):
  near ",": syntax error
grid-nasa-lvis-l2/grids_cut_shots.sh: line 79: fio: command not found
ogr2ogr -overwrite -gt 1000000 -f SQLite -dialect SQLITE -sql SELECT
*,
ST_Area(geometry) AS ac_by_shot,
ST_Distance(MakePoint(geasting, gnorthing, ), MakePoint(easting, northing, )) AS dist_shot2pixel
FROM LVIS2_ABoVE2017_0630_R1803_069010_shot_segments LVIS2_ABoVE2017_0630_R1803_069010_shot_segments.sqlite ./tmp.LZvUxfcFi4/tmp.7smTlSCJXd.sqlite -dsco SPATIALITE=YES -lco SPATIAL_INDEX=YES -nln LVIS2_ABoVE2017_0630_R1803_069010_shot_segments -nlt POLYGON
	- 'VirtualXPath'	[XML Path Language - XPath]
	- 'VirtualXPath'	[XML Path Language - XPath]
ERROR 1: In ExecuteSQL(): sqlite3_prepare_v2(SELECT
*,
ST_Area(geometry) AS ac_by_shot,
ST_Distance(MakePoint(geasting, gnorthing, ), MakePoint(easting, northing, )) AS dist_shot2pixel
FROM LVIS2_ABoVE2017_0630_R1803_069010_shot_segments):
  near ")": syntax error

bash grid-nasa-lvis-l2/shot_seg_to_point_grids.sh LVIS2_ABoVE2017_0630_R1803_069010_shot_segments.sqlite LVIS2_ABoVE2017_0630_R1803_069010_grid_points.sqlite 20.0 rh10

ERROR 1: In ExecuteSQL(): sqlite3_prepare_v2(SELECT SRID(geometry) FROM LVIS2_ABoVE2017_0630_R1803_069010_shot_segments LIMIT 1):
  no such table: LVIS2_ABoVE2017_0630_R1803_069010_shot_segments
ogr2ogr -overwrite -gt 1000000 -f SQLite -dialect SQLITE -sql SELECT
MakePoint(AVG(easting), AVG(northing), ) AS geometry,
COUNT(seq_id) AS shot_count,
ST_Area(ST_Union(geometry))/(20.0*20.0) AS sc_percent,
AVG(easting) AS easting, AVG(northing) AS northing, AVG(covered) AS covered, AVG(seq_id) AS seq_id, AVG(lon) AS lon, AVG(lat) AS lat,
AVG(glon) AS glon_avg, MIN(glon) AS glon_min, MAX(glon) AS glon_max, SUM(glon*ac_by_shot)/SUM(ac_by_shot) AS glon_wt_avg, AVG(glat) AS glat_avg, MIN(glat) AS glat_min, MAX(glat) AS glat_max, SUM(glat*ac_by_shot)/SUM(ac_by_shot) AS glat_wt_avg, AVG(zg) AS zg_avg, MIN(zg) AS zg_min, MAX(zg) AS zg_max, SUM(zg*ac_by_shot)/SUM(ac_by_shot) AS zg_wt_avg, AVG(tlon) AS tlon_avg, MIN(tlon) AS tlon_min, MAX(tlon) AS tlon_max, SUM(tlon*ac_by_shot)/SUM(ac_by_shot) AS tlon_wt_avg, AVG(tlat) AS tlat_avg, MIN(tlat) AS tlat_min, MAX(tlat) AS tlat_max, SUM(tlat*ac_by_shot)/SUM(ac_by_shot) AS tlat_wt_avg, AVG(zt) AS zt_avg, MIN(zt) AS zt_min, MAX(zt) AS zt_max, SUM(zt*ac_by_shot)/SUM(ac_by_shot) AS zt_wt_avg, AVG(azimuth) AS azimuth_avg, MIN(azimuth) AS azimuth_min, MAX(azimuth) AS azimuth_max, SUM(azimuth*ac_by_shot)/SUM(ac_by_shot) AS azimuth_wt_avg, AVG(incidentan) AS incidentan_avg, MIN(incidentan) AS incidentan_min, MAX(incidentan) AS incidentan_max, SUM(incidentan*ac_by_shot)/SUM(ac_by_shot) AS incidentan_wt_avg, AVG(range) AS range_avg, MIN(range) AS range_min, MAX(range) AS range_max, SUM(range*ac_by_shot)/SUM(ac_by_shot) AS range_wt_avg, AVG(geasting) AS geasting_avg, MIN(geasting) AS geasting_min, MAX(geasting) AS geasting_max, SUM(geasting*ac_by_shot)/SUM(ac_by_shot) AS geasting_wt_avg, AVG(gnorthing) AS gnorthing_avg, MIN(gnorthing) AS gnorthing_min, MAX(gnorthing) AS gnorthing_max, SUM(gnorthing*ac_by_shot)/SUM(ac_by_shot) AS gnorthing_wt_avg, AVG(ac_by_shot) AS ac_by_shot_avg, MIN(ac_by_shot) AS ac_by_shot_min, MAX(ac_by_shot) AS ac_by_shot_max, SUM(ac_by_shot*ac_by_shot)/SUM(ac_by_shot) AS ac_by_shot_wt_avg, AVG(dist_shot2pixel) AS dist_shot2pixel_avg, MIN(dist_shot2pixel) AS dist_shot2pixel_min, MAX(dist_shot2pixel) AS dist_shot2pixel_max, SUM(dist_shot2pixel*ac_by_shot)/SUM(ac_by_shot) AS dist_shot2pixel_wt_avg, AVG(rh10) AS rh10_avg, MIN(rh10) AS rh10_min, MAX(rh10) AS rh10_max, SUM(rh10*ac_by_shot)/SUM(ac_by_shot) AS rh10_wt_avg
FROM LVIS2_ABoVE2017_0630_R1803_069010_shot_segments
GROUP BY seq_id LVIS2_ABoVE2017_0630_R1803_069010_grid_points.sqlite LVIS2_ABoVE2017_0630_R1803_069010_shot_segments.sqlite -dsco SPATIALITE=YES -lco SPATIAL_INDEX=YES -nln LVIS2_ABoVE2017_0630_R1803_069010_grid_points -nlt POINT
	- 'VirtualXPath'	[XML Path Language - XPath]
	- 'VirtualXPath'	[XML Path Language - XPath]
ERROR 1: In ExecuteSQL(): sqlite3_prepare_v2(SELECT
MakePoint(AVG(easting), AVG(northing), ) AS geometry,
COUNT(seq_id) AS shot_count,
ST_Area(ST_Union(geometry))/(20.0*20.0) AS sc_percent,
AVG(easting) AS easting, AVG(northing) AS northing, AVG(covered) AS covered, AVG(seq_id) AS seq_id, AVG(lon) AS lon, AVG(lat) AS lat,
AVG(glon) AS glon_avg, MIN(glon) AS glon_min, MAX(glon) AS glon_max, SUM(glon*ac_by_shot)/SUM(ac_by_shot) AS glon_wt_avg, AVG(glat) AS glat_avg, MIN(glat) AS glat_min, MAX(glat) AS glat_max, SUM(glat*ac_by_shot)/SUM(ac_by_shot) AS glat_wt_avg, AVG(zg) AS zg_avg, MIN(zg) AS zg_min, MAX(zg) AS zg_max, SUM(zg*ac_by_shot)/SUM(ac_by_shot) AS zg_wt_avg, AVG(tlon) AS tlon_avg, MIN(tlon) AS tlon_min, MAX(tlon) AS tlon_max, SUM(tlon*ac_by_shot)/SUM(ac_by_shot) AS tlon_wt_avg, AVG(tlat) AS tlat_avg, MIN(tlat) AS tlat_min, MAX(tlat) AS tlat_max, SUM(tlat*ac_by_shot)/SUM(ac_by_shot) AS tlat_wt_avg, AVG(zt) AS zt_avg, MIN(zt) AS zt_min, MAX(zt) AS zt_max, SUM(zt*ac_by_shot)/SUM(ac_by_shot) AS zt_wt_avg, AVG(azimuth) AS azimuth_avg, MIN(azimuth) AS azimuth_min, MAX(azimuth) AS azimuth_max, SUM(azimuth*ac_by_shot)/SUM(ac_by_shot) AS azimuth_wt_avg, AVG(incidentan) AS incidentan_avg, MIN(incidentan) AS incidentan_min, MAX(incidentan) AS incidentan_max, SUM(incidentan*ac_by_shot)/SUM(ac_by_shot) AS incidentan_wt_avg, AVG(range) AS range_avg, MIN(range) AS range_min, MAX(range) AS range_max, SUM(range*ac_by_shot)/SUM(ac_by_shot) AS range_wt_avg, AVG(geasting) AS geasting_avg, MIN(geasting) AS geasting_min, MAX(geasting) AS geasting_max, SUM(geasting*ac_by_shot)/SUM(ac_by_shot) AS geasting_wt_avg, AVG(gnorthing) AS gnorthing_avg, MIN(gnorthing) AS gnorthing_min, MAX(gnorthing) AS gnorthing_max, SUM(gnorthing*ac_by_shot)/SUM(ac_by_shot) AS gnorthing_wt_avg, AVG(ac_by_shot) AS ac_by_shot_avg, MIN(ac_by_shot) AS ac_by_shot_min, MAX(ac_by_shot) AS ac_by_shot_max, SUM(ac_by_shot*ac_by_shot)/SUM(ac_by_shot) AS ac_by_shot_wt_avg, AVG(dist_shot2pixel) AS dist_shot2pixel_avg, MIN(dist_shot2pixel) AS dist_shot2pixel_min, MAX(dist_shot2pixel) AS dist_shot2pixel_max, SUM(dist_shot2pixel*ac_by_shot)/SUM(ac_by_shot) AS dist_shot2pixel_wt_avg, AVG(rh10) AS rh10_avg, MIN(rh10) AS rh10_min, MAX(rh10) AS rh10_max, SUM(rh10*ac_by_shot)/SUM(ac_by_shot) AS rh10_wt_avg
FROM LVIS2_ABoVE2017_0630_R1803_069010_shot_segments
GROUP BY seq_id):
  near ")": syntax error
Traceback (most recent call last):
  File "grid-nasa-lvis-l2/grid_lvis_l2.py", line 163, in <module>
    main(cmdargs)
  File "grid-nasa-lvis-l2/grid_lvis_l2.py", line 154, in main
    subprocess.run(cmd)
  File "/data2/sserbin/conda_envs/geospatial/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/data2/sserbin/conda_envs/geospatial/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/data2/sserbin/conda_envs/geospatial/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'fio'
```

It builds the shapefiles but crashes when gridding. Looks like CRS issue?  I am running as

```
python grid-nasa-lvis-l2/grid_lvis_l2.py -r 20 --out_srs EPSG:3156 --column_type lvis_l2_column_types.csvt \
--column2grid rh10 -- LVIS2_ABoVE2017_0630_R1803_069010.TXT LVIS2_ABoVE2017_0630_R1803_069010_grid_points.sqlite
```

And if I try with 2019 data I dont even get this far, it throughs an error about an incorrect field "The."  Any ideas?  Also do you think this will work with the 2019 C2 and F2 L2 data?  Thanks!

**Comment by serbinsh** [comment]
I can run the steps shown above

```(/data2/sserbin/conda_envs/geospatial) [sserbin@modex LVIS]$ ython grid-nasa-lvis-l2/rasterize_vector.py --at --burn 1 -l LVIS2_ABoVE2017_0630_R1803_069010_shot_circles -f GTiff --ot Byte --init 0 --nodata 0 -r 20.0 LVIS2_ABoVE2017_0630_R1803_069010_shot_circles.shp LVIS2_ABoVE2017_0630_R1803_069010_shot_cover.tif
-bash: ython: command not found
(/data2/sserbin/conda_envs/geospatial) [sserbin@modex LVIS]$ python grid-nasa-lvis-l2/rasterize_vector.py --at --burn 1 -l LVIS2_ABoVE2017_0630_R1803_069010_shot_circles -f GTiff --ot Byte --init 0 --nodata 0 -r 20.0 LVIS2_ABoVE2017_0630_R1803_069010_shot_circles.shp LVIS2_ABoVE2017_0630_R1803_069010_shot_cover.tif
gdal_rasterize -l LVIS2_ABoVE2017_0630_R1803_069010_shot_circles -a_nodata 0.0 -init 0.0 -ot Byte -burn 1.0 -at -tr 20.0 20.0 LVIS2_ABoVE2017_0630_R1803_069010_shot_circles.shp LVIS2_ABoVE2017_0630_R1803_069010_shot_cover.tif
0...10...20...30...40...50...60...70...80...90...100 - done.
(/data2/sserbin/conda_envs/geospatial) [sserbin@modex LVIS]$ gdal_rasterize -l LVIS2_ABoVE2017_0630_R1803_069010_shot_circles -a_nodata 0.0 -init 0.0 -ot Byte -burn 1.0 -at -tr 20.0 20.0 LVIS2_ABoVE2017_0630_R1803_069010_shot_circles.shp LVIS2_ABoVE2017_0630_R1803_069010_shot_cover.tif
0...10...20...30...40...50...60...70...80...90...100 - done.
(/data2/sserbin/conda_envs/geospatial) [sserbin@modex LVIS]$ bash grid-nasa-lvis-l2/raster_to_polygon_grids.sh LVIS2_ABoVE2017_0630_R1803_069010_shot_cover.tif LVIS2_ABoVE2017_0630_R1803_069010_shot_cover.shp
Input file size is 437, 380
0...10...20...30...40...50...60...70...80...90...100 - done.
ERROR 1: Translating source or target SRS failed:

BOUNDCRS[
    SOURCECRS[
        PROJCRS["unknown",
            BASEGEOGCRS["unknown",
                DATUM["Unknown based on GRS80 ellipsoid",
                    ELLIPSOID["GRS 1980",6378137,298.257222101,
                        LENGTHUNIT["metre",1],
                        ID["EPSG",7019]]],
```

but it seems to crash on 

```
bash grid-nasa-lvis-l2/raster_to_polygon_grids.sh LVIS2_ABoVE2017_0630_R1803_069010_shot_cover.tif LVIS2_ABoVE2017_0630_R1803_069010_shot_cover.shp
```

**Comment by zhanlilz** [comment]
@serbinsh I just updated the code and put up [a new pre-release](https://github.com/zhanlilz/grid-nasa-lvis-l2/releases/tag/v0.0-beta.1). The return from the old gdalinfo program was not structured enough to ensure accurate extraction of CRS info, which caused the trouble. Let me know if it works now. 

I only tried on the same 2017 file on a Linux system. I haven't yet tried 2019 files yet. Do 2019 files have the same column names as the 2017 ones? If so, it should work. Otherwise, some tweak at [here](https://github.com/zhanlilz/grid-nasa-lvis-l2/blob/402b0e9e97eb64c530a9846494a9af50d66cad17/vectorize_lvis_l2.sh#L40) and [here](https://github.com/zhanlilz/grid-nasa-lvis-l2/blob/402b0e9e97eb64c530a9846494a9af50d66cad17/shot_seg_to_point_grids.sh#L47) are needed.
